#!/usr/bin/env python3
# generator/gen_tests.py

"""
Генератор параметризованных NUnit-тестов на основе YAML-спецификации.
Читает формальное описание, преобразует классы эквивалентности в [TestCase],
генерирует структуру Arrange-Act-Assert и сохраняет файл в указанный каталог.
Зависимости: pyyaml (pip install pyyaml)
"""

import yaml
import argparse
import os
from pathlib import Path
from typing import Dict, List, Any

# Шаблон для одного TestCase внутри параметризованного теста
TEST_CASE_TEMPLATE = r'        [TestCase({inputs})]'

# Шаблон для всего тестового метода с параметризацией
TEST_METHOD_TEMPLATE = r'''
    [Test]
    [TestCaseSource(nameof(Get{method_name}TestCases))]
    public void {method_name}_Test(double input, double expected, bool shouldThrow)
    {{
        // Arrange
        // Act & Assert
        if (shouldThrow)
        {{
            Assert.Throws<ArgumentOutOfRangeException>(() => _converter.{method_name}(input));
        }}
        else if (double.IsNaN(expected))
        {{
            Assert.That(double.IsNaN(_converter.{method_name}(input)), Is.True);
        }}
        else
        {{
            double result = _converter.{method_name}(input);
            Assert.That(result, Is.EqualTo(expected).Within(0.001));
        }}
    }}

    private static IEnumerable<TestCaseData> Get{method_name}TestCases()
    {{
        yield return new TestCaseData(25.0, 298.15, false).SetName("{method_name}_NormalValue");
        yield return new TestCaseData(-273.15, 0.0, false).SetName("{method_name}_AbsoluteZero");
        yield return new TestCaseData(-274.0, 0.0, true).SetName("{method_name}_BelowAbsoluteZero_ThrowsException");
        yield return new TestCaseData(double.NaN, double.NaN, false).SetName("{method_name}_NaN_ReturnsNaN");
    }}
}}

# Шаблон всего файла тестов
TEST_FILE_TEMPLATE = '''// <auto-generated>
// AUTO-GENERATED TESTS. DO NOT EDIT MANUALLY.
// Source: {spec_source}
// Generator: gen_tests.py v1.0

using NUnit.Framework;
using Lab.Interfaces;

namespace Lab.Tests.Generated
{{
    [TestFixture]
    public class {test_class_name}
    {{
        private ITemperatureConverter _converter;

        [SetUp]
        public void SetUp()
        {{
            // Используйте конкретную реализацию или внедряйте через конструктор
            _converter = new Lab.Implementations.GenCode1.TemperatureConverter();
        }}

        {test_methods}
    }}
}}

def format_csharp_input(value: Any) -> str:
    """Преобразует значение из YAML в литерал C#."""
    if isinstance(value, str):
        if value == "double.NaN":
            return "double.NaN"
        return f'"{value}"'
    elif isinstance(value, bool):
        return "true" if value else "false"
    elif value is None:
        return "null"
    else:
        return str(value)

def generate_method_tests(method_data: Dict[str, Any]) -> List[str]:
    """Генерирует один метод теста с параметризацией для всех классов эквивалентности."""
    method_name = method_data["name"]
    
    # Строим список TestCaseData
    test_cases = []
    for eq_class in method_data.get("equivalence_classes", []):
        input_val = eq_class["inputs"][0]  # у нас всегда 1 параметр
        expected_raw = eq_class["expected"]
        should_throw = expected_raw == "ArgumentOutOfRangeException"
        
        if expected_raw == "double.NaN":
            expected = "double.NaN"
        else:
            try:
                expected = float(expected_raw)
            except ValueError:
                expected = 0.0
        
        test_cases.append((input_val, expected, should_throw))
    
    # Генерируем yield-ы для TestCaseSource
    yields = []
    for i, (inp, exp, throw) in enumerate(test_cases):
        inp_str = format_csharp_input(inp)
        exp_str = "double.NaN" if exp == "double.NaN" else str(exp)
        throw_str = "true" if throw else "false"
        yields.append(f'        yield return new TestCaseData({inp_str}, {exp_str}, {throw_str});')
    
    test_cases_source = '\n'.join(yields)
    
    # Шаблон метода с TestCaseSource
    method_template = f'''
    [Test]
    [TestCaseSource(nameof(Get{method_name}TestCases))]
    public void {method_name}_Test(double input, double expected, bool shouldThrow)
    {{
        if (shouldThrow)
        {{
            Assert.Throws<ArgumentOutOfRangeException>(() => _converter.{method_name}(input));
        }}
        else if (double.IsNaN(expected))
        {{
            Assert.That(double.IsNaN(_converter.{method_name}(input)), Is.True);
        }}
        else
        {{
            double result = _converter.{method_name}(input);
            Assert.That(result, Is.EqualTo(expected).Within(0.001));
        }}
    }}

    private static IEnumerable<TestCaseData> Get{method_name}TestCases()
    {{
{test_cases_source}
    }}
    return [method_template]

def render_and_save(spec: Dict[str, Any], config: Dict[str, Any]) -> None:
    """Собирает полный файл тестов и сохраняет на диск."""
    module_name = spec["module"]
    test_class_name = config.get("test_class_name", f"{module_name}Tests_Generated")
    
    test_methods = []
    for method in spec["methods"]:
        test_methods.extend(generate_method_tests(method))
    
    tests_block = "\n".join(test_methods)
    
    file_content = TEST_FILE_TEMPLATE.format(
        spec_source=config.get("spec_path", "N/A"),
        test_class_name=test_class_name,
        test_methods=tests_block
    )
    
    out_dir = Path(config.get("output_dir", "Tests"))
    out_dir.mkdir(parents=True, exist_ok=True)
    output_file = out_dir / f"{test_class_name}.Generated.cs"
    
    output_file.write_text(file_content, encoding="utf-8")
    print(f"[√] Сгенерирован файл: {output_file}")
    print(f"    Методов покрыто: {len(spec['methods'])}")
    total_tests = sum(len(m.get('equivalence_classes', [])) for m in spec['methods'])
    print(f"    Тестов сгенерировано: {total_tests}")

def load_spec(spec_path: str) -> Dict[str, Any]:
    """Безопасная загрузка YAML-спецификации."""
    with open(spec_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="C# NUnit Test Generator from YAML Spec")
    parser.add_argument("--config", default="config.yaml", help="Путь к config.yaml")
    args = parser.parse_args()
    
    print("[*] Загрузка конфигурации...")
    with open(args.config, 'r', encoding='utf-8') as f:
        config = yaml.safe_load(f)
    
    print(f"[*] Загрузка спецификации: {config['spec_path']}...")
    spec_data = load_spec(config['spec_path'])
    
    print("[*] Генерация C# тестов...")
    render_and_save(spec_data, config)
    print("[√] Готово.")
